#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Deteniendo monitor de apagado...\n"
sudo update-rc.d listen-for-shutdown.sh remove
sudo /etc/init.d/listen-for-shutdown.sh stop

echo "=> Removiendo monitor de apagado...\n"
sudo rm -rf /usr/local/bin/listen-for-shutdown.py 
sudo rm -rf /etc/init.d/listen-for-shutdown.sh 

echo "Monitor de apagado desinstalado.\n"
echo "Visita SAandT en YOUTUBE para mas tutoriales"
